spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/dcbapp
    password: Emmanuel@1803
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to daily code buffer!!!!
server:
  port: '8082'
  error:
    include-message: always